apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-dtgz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-dtgz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-dtgz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-dtgz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-dtgz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wczz-tenant/rhtap-demo-app/hacbs-test-project-dtgz@sha256:9acca1c4fdeadf1228cc4b06e75b0c136dc530d2c533dc1cca3920558f0be8df
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
